### ISSUE TITLE
edx_notes postgres password not updating automatically

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1354]
Consul template doesn't always seem to be monitoring the lease associated with the postgres password for edx_notes. After 30 days these messages show up:

```
compose-notes_api-1  | 2023-02-08 19:52:55,853 ERROR 9 [django.request] log.py:224 - Internal Server Error: /api/v1/annotations/
compose-notes_api-1  | Traceback (most recent call last):
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
compose-notes_api-1  |     self.connect()
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
compose-notes_api-1  |     return func(*args, **kwargs)
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
compose-notes_api-1  |     self.connection = self.get_new_connection(conn_params)
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
compose-notes_api-1  |     return func(*args, **kwargs)
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
compose-notes_api-1  |     connection = Database.connect(**conn_params)
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
compose-notes_api-1  |     return Connection(*args, **kwargs)
compose-notes_api-1  |   File "/app/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
compose-notes_api-1  |     super().__init__(*args, **kwargs2)
compose-notes_api-1  | MySQLdb.OperationalError: (1045, "Access denied for user 'v-note-0aJ6lvxOP'@'10.8.2.187' (using password: YES)")
compose-notes_api-1  |

```

Can be resolved with `pkill -9 consul-template` or just initiating an instance refresh. Either way that is 👎 so we should figure out why consul-template isn't doing the needful and keeping an eye on those leases. Maybe only vault-template monitors leases? That would be ... extremely disappointing if true.

**Comment by pdpinch** [comment]
FYI @cachob

**Comment by Ardiea** [comment]
Maybe related? 

https://github.com/hashicorp/consul-template/issues/1161
https://github.com/hashicorp/consul-template/issues/1224
https://github.com/hashicorp/consul-template/pull/1269
