### ISSUE TITLE
Migrate old OCW origin to a stable and low-maintenance service

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#2528]
### Description/Context

The OCW team would like to keep the old OCW origin for an indeterminate amount of time. Currently it is an EC2 instance running Nginx and keeping all of the static content on disk. To reduce the amount of overhead to keep it running we want to either manage the instance as infrastructure code, or migrate the content into a serverless environment.

### Plan/Design

- [x] Determine whether to keep the system as an Nginx server or move to e.g. S3 and Fastly or some other static hosting service
- [x] Migrate all content to the target environment
- [x] Set up monitoring with a P3 priority to ensure that the site stays up

**Comment by feoh** [comment]
OK so my plan for this is to [rclone](https://github.com/rclone/rclone) the instance's contents to an S3 bucket fronted by Fastly unless I find some really compelling reason not to. It'll be much more reliable and lower maintenance than running an instance and putting it under Pulumi control.

**Comment by feoh** [comment]
The nginx config looks like this. Seems like in addition to providing the content route we only really need to worry about the /courses/edx_coursees.json path:
```
#
# **** DO NOT EDIT THIS FILE ****
#
# This file is managed by Salt.

server {
    server_name ocw-origin.odl.mit.edu;
    listen 80;
    listen [::]:80;

    location ~ /.well-known {
        allow all;
    }

    location /courses/edx_courses.json {
        root /var/www/ocw;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    server_name ocw-origin.odl.mit.edu;
    listen 443 ssl default_server;
    listen [::]:443 ssl;
    root /var/www/ocw;
    ssl_certificate /etc/nginx/ssl/odl_wildcard.crt;
    ssl_certificate_key /etc/nginx/ssl/odl_wildcard.key;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
56:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256;56-SHA256:DHE-RSA-AES128-SHA2--More--(76%)
    ssl_prefer_server_ciphers on;
    resolver 1.1.1.1;

    location /status {
        return 200;
    }

    location / {
        try_files $uri $uri/index.htm =404;
        error_page 404 /jsp/error.html;
        rewrite ^(/[^\.\?]+[^/])$ $1/ permanent;
    }
}
```

**Comment by feoh** [comment]
Decided to take @blarghmatey advice and port the s3_site_cloudfront Pulumi service to BucketV2 so we can use it to build the site.

That's done. Now I just need the code to build the site with the service.

**Comment by feoh** [comment]
So, I was getting an error around missing ownership controls, and Tobias pointed me at appropriate prior art from ocw-site's Pulumi project.

Unfortunately incorporating that required that I restructure pretty much the entire code section around the S3 website bucket creation, which had a bunch of fiddly bits.

I did that, and pulumi update runs, but I get some output I'm not wild about and will talk with @blarghmatey about tomorrow:
```
~/src/mit/ol-infrastructure/src/ol_infrastructure/infrastructure/aws/s3_sites (cpatti_update_s3_cf_to_v2*) » pr pulumi up -s infrastructure.aws.s3_sites.Production
Previewing update (infrastructure.aws.s3_sites.Production):
     Type                                       Name                                                             Plan       Info
     pulumi:pulumi:Stack                        ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production             2 messages
 +   ├─ aws:s3:BucketV2                         ocw-legacy-bucket                                                create
 +   ├─ aws:s3:BucketV2                         xpro-legacy-certificates-bucket                                  create
     ├─ ol:infrastructure:aws:S3ServerlessSite  ocw-legacy
 +   │  └─ aws:cloudfront:Distribution          ocw-legacy-cloudfront-distribution                               create
 +   ├─ aws:s3:BucketCorsConfigurationV2        ('xpro-legacy-certificates-bucket',)-cors                        create
 +   ├─ aws:s3:BucketWebsiteConfigurationV2     ('xpro-legacy-certificates-bucket',)-website                     create
 +   ├─ aws:s3:BucketCorsConfigurationV2        ('ocw-legacy-bucket',)-cors                                      create
 +   ├─ aws:s3:BucketPublicAccessBlock          ('xpro-legacy-certificates-bucket',)-public-access               create
 +   ├─ aws:s3:BucketPublicAccessBlock          ('ocw-legacy-bucket',)-public-access                             create
 +   ├─ aws:s3:BucketVersioningV2               ('xpro-legacy-certificates-bucket',)-versioning                  create
 +   ├─ aws:s3:BucketVersioningV2               ('ocw-legacy-bucket',)-versioning                                create
 +   ├─ aws:s3:BucketWebsiteConfigurationV2     ('ocw-legacy-bucket',)-website                                   create
 +   ├─ aws:s3:BucketOwnershipControls          ('xpro-legacy-certificates-bucket',)-ownership-controls          create
 +   ├─ aws:s3:BucketOwnershipControls          ('ocw-legacy-bucket',)-ownership-controls                        create
 +   ├─ aws:s3:BucketPolicy                     ('xpro-legacy-certificates-bucket',)-policy                      create
     ├─ ol:infrastructure:aws:S3ServerlessSite  xpro-legacy-certificates
 ~   │  ├─ aws:cloudfront:Distribution          xpro-legacy-certificates-cloudfront-distribution                 update     [diff: ~origins]
 -   │  └─ aws:s3:BucketV2                      xpro-legacy-certificates-bucket                                  delete
 +   ├─ aws:s3:BucketPolicy                     ('ocw-legacy-bucket',)-policy                                    create
 +   └─ aws:route53:Record                      ocw-legacy-domain                                                create

Diagnostics:
  pulumi:pulumi:Stack (ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production):
    site_bucket_policy: <pulumi_aws.s3.bucket_policy.BucketPolicy object at 0x7f57d4a8f2c0>
    site_bucket_policy: <pulumi_aws.s3.bucket_policy.BucketPolicy object at 0x7f57d443de50>

Outputs:
  + ocw_legacy_acm_cname      : "ocw-legacy.ocw.mit.edu"
  + ocw_legacy_bucket         : "ocw-legacy"
  + ocw_legacy_distribution_id: output<string>

Resources:
    + 16 to create
    ~ 1 to update
    - 1 to delete
    18 changes. 6 unchanged

Do you want to perform this update? yes
Updating (infrastructure.aws.s3_sites.Production):
     Type                 Name                                                             Status                  Info
     pulumi:pulumi:Stack  ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production  **failed**              1 error; 2 messages
 +   ├─ aws:s3:BucketV2   ocw-legacy-bucket                                                created (1s)
 +   └─ aws:s3:BucketV2   xpro-legacy-certificates-bucket                                  **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production):
    site_bucket_policy: <pulumi_aws.s3.bucket_policy.BucketPolicy object at 0x7f4370ec4d70>
    site_bucket_policy: <pulumi_aws.s3.bucket_policy.BucketPolicy object at 0x7f4370919a00>
    error: update failed

  aws:s3:BucketV2 (xpro-legacy-certificates-bucket):
    error: 1 error occurred:
        * creating S3 Bucket (mitxpro-legacy-certificates): BucketAlreadyExists

Outputs:
  - xpro_certs_acm_cname      : "certificates.mitxpro.mit.edu"
  - xpro_certs_bucket         : "mitxpro-legacy-certificates"
  - xpro_certs_distribution_id: "EIYZB8MGJ5PFE"

Resources:
    + 1 created
    5 unchanged

Duration: 4s

```

**Comment by feoh** [comment]
After yesterday's rewrite I was getting an error about the cert being out of date. In response to which Tobias pointed me at [this](https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/components/aws/acm.py) ACM cert component which handles it.

So I rewrote the existing ACM nubbins in the stack to use it.

Today's problem, I'm mystified as to why my stack can't grab the ocw zone id from the DNS stack:

```
~/src/mit/ol-infrastructure/src/ol_infrastructure/infrastructure/aws/s3_sites (cpatti_update_s3_cf_to_v2) » pr pulumi up -s infrastructure.aws.s3_sites.Production                      feoh@prometheus
Previewing update (infrastructure.aws.s3_sites.Production):
     Type                                       Name                                                             Plan       Info
     pulumi:pulumi:Stack                        ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production             1 error
 +   ├─ aws:s3:BucketV2                         xpro-legacy-certificates-bucket                                  create
 +   ├─ aws:s3:BucketOwnershipControls          xpro-legacy-certificates-bucket-ownership-controls               create
 +   ├─ aws:s3:BucketPublicAccessBlock          xpro-legacy-certificates-bucket-public-access                    create
 +   ├─ aws:s3:BucketCorsConfigurationV2        xpro-legacy-certificates-bucket-cors                             create
 +   ├─ aws:s3:BucketVersioningV2               xpro-legacy-certificates-bucket-versioning                       create
 +   ├─ aws:s3:BucketWebsiteConfigurationV2     xpro-legacy-certificates-bucket-website                          create
     ├─ ol:infrastructure:aws:S3ServerlessSite  xpro-legacy-certificates
 ~   │  └─ aws:cloudfront:Distribution          xpro-legacy-certificates-cloudfront-distribution                 update     [diff: ~origins,viewerCertificate]
     └─ ol:infrastructure:aws:S3ServerlessSite  ocw-legacy
 +      └─ aws:cloudfront:Distribution          ocw-legacy-cloudfront-distribution                               create

Diagnostics:
  pulumi:pulumi:Stack (ol-infrastructure-aws-s3-infrastructure.aws.s3_sites.Production):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/feoh/.pulumi/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/home/feoh/.pyenv/versions/3.12.3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/home/feoh/.cache/pypoetry/virtualenvs/ol-infrastructure-ha13_Yh9-py3.12/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "/home/feoh/.cache/pypoetry/virtualenvs/ol-infrastructure-ha13_Yh9-py3.12/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 56, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/feoh/.cache/pypoetry/virtualenvs/ol-infrastructure-ha13_Yh9-py3.12/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 118, in wait_for_rpcs
        await task
    TypeError: Missing required property 'zone_id'

```

**Comment by feoh** [comment]
We'll handle migrating the old.ocw.mit.edu DNS record as well as monitoring in a follow on task which I'll add. For now though this is complete.
