### ISSUE TITLE
Build data-production EKS Stack & Open Metadata - Kubernetes Production

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#2731]
### Description/Context
What it says on the tin. Build all necessary components to get Open Metadata running in production at https://data.ol.mit.edu

### Plan/Design
- Follow the doc I just wrote [here](https://github.com/mitodl/ol-infrastructure/issues/2730).
- Augment doc as necessary as I go in case I missed anything

**Comment by feoh** [comment]
Initial configuration written for:
- EKS cluster
- EKS Substructure
- Networking infra

I'm running into an error with the networking stuff. I suspect I'm allocating my subnets wrong:

```
Diagnostics:
  pulumi:pulumi:Stack (ol-infrastructure-networking-infrastructure.aws.network.Production):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/feoh/src/mit/ol-infrastructure/src/ol_infrastructure/infrastructure/aws/network/__main__.py", line 84, in <module>
        data_vpc_config = OLVPCConfig(
                          ^^^^^^^^^^^^
      File "/home/feoh/src/mit/ol-infrastructure/src/ol_infrastructure/lib/ol_types.py", line 73, in __init__
        super().__init__(**kwargs)
      File "/home/feoh/.cache/pypoetry/virtualenvs/ol-infrastructure-ha13_Yh9-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
        validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    pydantic_core._pydantic_core.ValidationError: 1 validation error for OLVPCConfig
    k8s_service_subnet
      Input is not a valid IPv4 network [type=ip_v4_network, input_value='10.110.83.0/23', input_type=str]

```

With any luck @Ardiea will look at [my change](https://github.com/mitodl/ol-infrastructure/commit/e2a51cbf9d8ceda3bad071a419d1504861e4453d) tomorrow.
