### ISSUE TITLE
edX Forum can't connect to Mongo Atlas

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#469]
The forum service for Open edX is throwing errors when trying to connect to establish a connection with Mongo Atlas. 

```
/edx/app/forum/.gem/ruby/2.5.0/gems/mongo-2.5.3/lib/mongo/server_selector/selectable.rb:110:in `select_server': No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47025239772020 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015 (Mongo::Error::NoServerAvailable)
	from /edx/app/forum/.gem/ruby/2.5.0/gems/mongo-2.5.3/lib/mongo/collection/view/iterable.rb:41:in `block in each'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/mongo-2.5.3/lib/mongo/retryable.rb:44:in `read_with_retry'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/mongo-2.5.3/lib/mongo/collection/view/iterable.rb:40:in `each'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/mongoid-7.0.5/lib/mongoid/query_cache.rb:227:in `each'
	from /edx/app/forum/cs_comments_service/app.rb:173:in `map'
	from /edx/app/forum/cs_comments_service/app.rb:173:in `<top (required)>'
	from config/unicorn_tcp.rb:4:in `require'
	from config/unicorn_tcp.rb:4:in `reload'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/lib/unicorn/configurator.rb:84:in `instance_eval'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/lib/unicorn/configurator.rb:84:in `reload'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/lib/unicorn/configurator.rb:77:in `initialize'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:77:in `new'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:77:in `initialize'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/bin/unicorn:126:in `new'
	from /edx/app/forum/.gem/ruby/2.5.0/gems/unicorn-5.3.1/bin/unicorn:126:in `<top (required)>'
	from /edx/app/forum/cs_comments_service/bin/unicorn:16:in `load'
	from /edx/app/forum/cs_comments_service/bin/unicorn:16:in `<main>'
```

**Comment by blarghmatey** [comment]
The problem was due to the missing replica set identifier in the connection string which is now included in the configuration template.
